"""Adding a field in Enquiry Table

Revision ID: 9a72ff6ef2d7
Revises: 576256090f76
Create Date: 2024-11-20 17:00:04.959754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a72ff6ef2d7'
down_revision = '576256090f76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiries', sa.Column('is_approved', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enquiries', 'is_approved')
    # ### end Alembic commands ###
