from faker import Faker
from sqlalchemy.orm import Session

from app.models.user import User

fake = Faker()

class ProspectFactory:
    @staticmethod
    def create(db: Session):
        """
        Generate a fake user and insert into the database.
        """
        user = User(
            email=fake.email(),
            password=fake.password(length=12)
        )
        db.add(user)
        db.commit()
        db.refresh(user)  # Refresh to get the ID and other autogenerated fields
        return user